spring.application.name=devops-demo
server.port=8081
spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongo:27017/devopsdemo}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
